### ISSUE TITLE
Data feed uncaught exception

### ISSUE THREAD

**Issue by austin3dickey** [Geotab/mygeotab-python#130]
Hey there,

First off, thank you for this client! This is super useful for data scientists fluent in Python.

I've been running a `DataFeed` for a few months now to sync `StatusData` with my local database. I've noticed that the job fails every Sunday at midnight with the following traceback:

```
Traceback (most recent call last):
  File ".../urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File ".../urllib3/util/connection.py", line 83, in create_connection
    raise err
  File ".../urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File ".../urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File ".../urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File ".../urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File ".../urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File ".../urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f5e031f5978>: Failed to establish a new connection: [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File ".../requests/adapters.py", line 440, in send
    timeout=timeout
  File ".../urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File ".../urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='my224.geotab.com', port=443): Max retries exceeded with url: /apiv1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5e031f5978>: Failed to establish a new connection: [Errno 110] Connection timed out',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File ".../kick_off.py", line 99, in stream_data
    my_feed.start(threaded=False)
  File ".../mygeotab/ext/feed.py", line 94, in start
    self._run()
  File ".../mygeotab/ext/feed.py", line 73, in _run
    from_version=self._version, results_limit=self.results_limit)
  File ".../mygeotab/api.py", line 94, in call
    result = _query(self._server, method, params, self.timeout, verify_ssl=self._is_verify_ssl)
  File ".../mygeotab/api.py", line 305, in _query
    verify=verify_ssl)
  File ".../requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File ".../requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File ".../requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File ".../requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='my224.geotab.com', port=443): Max retries exceeded with url: /apiv1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5e031f5978>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

I suspect there is some database maintenance or something that causes this to occur every Sunday at midnight. Would it be possible to catch `requests.exceptions.ConnectionError`s in the DataFeed and send them to the `on_error` listener method?

**Comment by aaronmader** [comment]
It looks like they might've improved some of the error handling around this exception - the errors I receive do propagate to on_error as OP requested.

I'm definitely seeing errors consistently every Sunday ("DbUnavailableException: Initializing"), followed by (temporary) authentication errors in the minutes following (InvalidUserException), as my code attempts to re-connect. Though obviously the source of those errors isn't with this python library.

Is there a documented workaround for these weekly errors?
